#!/usr/bin/env python3
"""
Sprite Forge Assembler — build a final sprite sheet + Hermes-readable JSON.

Two input paths:
  (A) From an analyzer.json (existing sheet): just re-export the JSON
      in Hermes's consumer format, optionally keying the background.
  (B) From a strips directory (generated by generator.py): detect each
      strip's frames via analyzer, place them on a grid, build the
      final sheet PNG + JSON.

The Hermes-readable JSON format is intentionally minimal:

    {
      "version": 1,
      "sheet": "path/to/sheet.png",
      "size": [W, H],
      "bg_mode": "transparent",
      "animations": {
        "idle":  {"frames": [[x,y,w,h], ...], "fps": 10, "loop": true},
        "walk":  {"frames": [[x,y,w,h], ...], "fps": 12, "loop": true},
        "punch": {"frames": [[x,y,w,h], ...], "fps": 15, "loop": false,
                  "frame_data": {"startup": 3, "active": 2, "recovery": 5}}
      }
    }

Any Hermes-generated 2D game can consume this format: load the PNG,
draw the frame at the current time, advance per animation. Genre data
(fighters: startup/active/recovery) travels in per-animation
`frame_data` when present.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from PIL import Image
import numpy as np

# Import analyzer from this same package
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from analyzer import analyze_sheet, export_keyed_sheet, find_frame_bounds, create_content_mask


# --- Public format ---------------------------------------------------

HERMES_JSON_VERSION = 1


def write_hermes_json(
    out_path: str,
    sheet_path: str,
    size: Tuple[int, int],
    animations: Dict[str, Dict],
    bg_mode: str = "transparent",
    meta: Optional[Dict] = None,
) -> str:
    """Write a Hermes-consumer JSON document."""
    doc = {
        "version": HERMES_JSON_VERSION,
        "sheet": os.path.basename(sheet_path),
        "size": list(size),
        "bg_mode": bg_mode,
        "animations": animations,
    }
    if meta:
        doc["meta"] = meta
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2)
    return out_path


# --- Path A: convert existing analyzer.json to Hermes format --------

def from_analyzer_json(
    analyzer_json_path: str,
    sheet_path: str,
    out_json: str,
    animation_name: str = "all",
    fps: int = 10,
    loop: bool = True,
) -> str:
    """Take an existing analyzer output (a flat list of frames, no
    animation names) and publish it as a Hermes JSON with one catch-all
    animation. Useful for external sprite sheets where you don't have
    per-animation labeling yet.
    """
    with open(analyzer_json_path, "r") as f:
        adata = json.load(f)

    frames = [f["bounds"] for f in adata.get("frames", [])]
    animations = {
        animation_name: {
            "frames": frames,
            "fps": fps,
            "loop": loop,
        }
    }
    size = adata.get("current_size") or adata.get("original_size") or [0, 0]
    return write_hermes_json(
        out_path=out_json,
        sheet_path=sheet_path,
        size=tuple(size),
        animations=animations,
        bg_mode=adata.get("bg_mode", "transparent"),
        meta={
            "source": "analyzer_json",
            "analyzer_input": os.path.basename(analyzer_json_path),
            "total_frames": adata.get("total_frames"),
            "rows": adata.get("rows"),
        },
    )


def from_analyzer_json_by_row(
    analyzer_json_path: str,
    sheet_path: str,
    out_json: str,
    row_names: Optional[List[str]] = None,
    default_fps: int = 10,
) -> str:
    """Convert an analyzer JSON into Hermes format, using each detected
    ROW as its own animation. Good for sheets where rows already
    correspond to logical animations (common convention)."""
    with open(analyzer_json_path, "r") as f:
        adata = json.load(f)

    row_groups = adata.get("row_groups", [])
    animations = {}
    for i, row in enumerate(row_groups):
        name = (row_names[i] if row_names and i < len(row_names) else f"row_{i}")
        frames = [f["bounds"] for f in row]
        animations[name] = {
            "frames": frames,
            "fps": default_fps,
            "loop": True,
        }

    size = adata.get("current_size") or adata.get("original_size") or [0, 0]
    return write_hermes_json(
        out_path=out_json,
        sheet_path=sheet_path,
        size=tuple(size),
        animations=animations,
        bg_mode=adata.get("bg_mode", "transparent"),
        meta={
            "source": "analyzer_json_by_row",
            "analyzer_input": os.path.basename(analyzer_json_path),
            "total_frames": adata.get("total_frames"),
            "rows": adata.get("rows"),
        },
    )


# --- Path B: assemble strips into a single sheet --------------------

def assemble_from_strips(
    generator_manifest: Dict,
    out_sheet: str,
    out_json: str,
    cell_w: int = 96,
    cell_h: int = 96,
    strip_gap: int = 10,
    row_gap: int = 10,
) -> Dict:
    """Stack each generated strip onto one big sheet, one per row.
    Detect frame bounds per strip via analyzer, record them in the
    final JSON with the animation name the strip was generated for.
    """
    strips = [s for s in generator_manifest.get("strips", []) if s.get("path")]
    if not strips:
        raise ValueError("manifest has no successful strips to assemble")

    # Final sheet dimensions: widest strip sets width; sum of heights + gaps
    strip_images = []
    for s in strips:
        img = Image.open(s["path"]).convert("RGBA")
        strip_images.append(img)
    sheet_w = max(img.size[0] for img in strip_images)
    sheet_h = sum(img.size[1] for img in strip_images) + \
              row_gap * max(0, len(strip_images) - 1)

    sheet = Image.new("RGBA", (sheet_w, sheet_h), (0, 0, 0, 0))

    # Paste each strip at the cumulative Y position
    animations = {}
    y_cursor = 0
    for strip_meta, img in zip(strips, strip_images):
        sheet.alpha_composite(img, (0, y_cursor))

        # Detect frames in this strip (within the strip's own coordinate
        # space) and translate them into sheet coordinates
        strip_arr = np.array(img.convert("RGBA"))
        mask = create_content_mask(strip_arr, bg_mode="auto")
        local_frames = find_frame_bounds(mask, min_width=8, min_height=8,
                                         padding=2)
        global_frames = [
            [int(x), int(y + y_cursor), int(w), int(h)]
            for (x, y, w, h) in local_frames
        ]

        anim_entry = {
            "frames": global_frames,
            "fps": _fps_for_animation(strip_meta.get("animation", "")),
            "loop": _loop_for_animation(strip_meta.get("animation", "")),
        }
        if strip_meta.get("frame_data"):
            anim_entry["frame_data"] = strip_meta["frame_data"]
        if strip_meta.get("state_id") is not None:
            anim_entry["state_id"] = strip_meta["state_id"]
        animations[strip_meta["animation"]] = anim_entry

        y_cursor += img.size[1] + row_gap

    os.makedirs(os.path.dirname(os.path.abspath(out_sheet)), exist_ok=True)
    sheet.save(out_sheet)

    write_hermes_json(
        out_path=out_json,
        sheet_path=out_sheet,
        size=(sheet_w, sheet_h),
        animations=animations,
        bg_mode="transparent",
        meta={
            "source": "generator_strips",
            "n_animations": len(animations),
            "strip_count": len(strips),
        },
    )
    return {
        "sheet": out_sheet,
        "json": out_json,
        "n_animations": len(animations),
        "size": [sheet_w, sheet_h],
    }


def _fps_for_animation(anim_name: str) -> int:
    """Heuristic FPS per animation type. Callers override in post."""
    a = (anim_name or "").lower()
    if "idle" in a or "wait" in a or "stand" in a:
        return 6
    if "walk" in a:
        return 10
    if "run" in a:
        return 12
    if "jump" in a:
        return 12
    if "punch" in a or "attack" in a or "kick" in a:
        return 15
    if "hit" in a or "block" in a or "hurt" in a:
        return 12
    if "sleep" in a or "down" in a:
        return 4
    return 10


def _loop_for_animation(anim_name: str) -> bool:
    """Heuristic loop/no-loop per animation type."""
    a = (anim_name or "").lower()
    # One-shot animations
    if any(k in a for k in ("punch", "attack", "kick", "hit", "hurt", "jump",
                             "death", "victory", "falling", "waking")):
        return False
    return True


# --- CLI -------------------------------------------------------------

def _cli():
    import argparse
    parser = argparse.ArgumentParser(description="Sprite Forge assembler")
    sub = parser.add_subparsers(dest="cmd")

    # Path A: from an existing analyzer JSON
    a = sub.add_parser("from-analyzer",
                        help="Convert analyzer.json to Hermes-consumer JSON")
    a.add_argument("--analyzer-json", required=True)
    a.add_argument("--sheet", required=True)
    a.add_argument("--out", required=True)
    a.add_argument("--by-row", action="store_true",
                   help="Treat each detected row as its own animation")
    a.add_argument("--row-names", nargs="+", default=None,
                   help="Names for each row (in order)")
    a.add_argument("--fps", type=int, default=10)

    # Path B: assemble strips
    b = sub.add_parser("from-strips",
                        help="Assemble generator output strips into one sheet")
    b.add_argument("--manifest", required=True,
                   help="JSON file with strips list (from generator)")
    b.add_argument("--out-sheet", required=True)
    b.add_argument("--out-json", required=True)

    args = parser.parse_args()
    if args.cmd == "from-analyzer":
        if args.by_row:
            path = from_analyzer_json_by_row(
                analyzer_json_path=args.analyzer_json,
                sheet_path=args.sheet,
                out_json=args.out,
                row_names=args.row_names,
                default_fps=args.fps,
            )
        else:
            path = from_analyzer_json(
                analyzer_json_path=args.analyzer_json,
                sheet_path=args.sheet,
                out_json=args.out,
                fps=args.fps,
            )
        print(f"wrote {path}")
    elif args.cmd == "from-strips":
        with open(args.manifest) as f:
            manifest = json.load(f)
        result = assemble_from_strips(
            generator_manifest=manifest,
            out_sheet=args.out_sheet,
            out_json=args.out_json,
        )
        print(json.dumps(result, indent=2))
    else:
        parser.print_help()


if __name__ == "__main__":
    _cli()
